### ISSUE TITLE
Possibility to use as an audio efect plugin

### ISSUE THREAD

**Issue by ssabug** [Mats7/M47X-Glitchmachine#1]
Hi,

First thank you for sharing your project, i am currently tryin to built it for linux in VST3

After getting the error, while trying to build the app as an audio plugin (VST3)  : 

`/usr/bin/ld: build/intermediate/Debug/include_juce_audio_plugin_client_VST3_dd633589.o: in function `juce::createPluginFilterOfType(juce::AudioProcessor::WrapperType)':`
`....../JUCE/modules/juce_audio_plugin_client/detail/juce_CreatePluginFilter.h:35: undefined reference to `createPluginFilter()'`

I looked more on the code and wondered if the Glitchmachine is supposed to be ran as an standalone app only?
If yes, what would be the stepsto turn it into a audio effect plugin, if it is even possible?

thank you for your answer

**Comment by Mats7** [comment]
Hello,

it was meant to run as a standalone app only and it was tested on
Win10/Win8.1.

This app was my first audio app project and it was part of my bachelor's
thesis. I had plans to make a plugin version of this app in the future, but
I haven't looked at it since June.

I may try to do it, but if this app had to be functional as an effect in
DAW, it would involve some major editing. For example:
The way the samples are being loaded into the buffers for further
processing.
The way the samples are processed in the individual effects.
Functions for audio playback (because that would be controlled mainly by
the DAW).
Optimalisation changes (because this app uses a lot of memory for what it
is doing… and also the audio processing in some parts can be improved).
And maybe other changes I cant think of right now.....
